// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1AtG1K9YimUCXKh_S-0lY8OcIL5zXVXg',
    appId: '1:1061517609461:web:eed36989b825344330f8bc',
    messagingSenderId: '1061517609461',
    projectId: 'assignment-1ecbe',
    authDomain: 'assignment-1ecbe.firebaseapp.com',
    storageBucket: 'assignment-1ecbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy2Vz0xvNmBGnq5RWbCCIKc-52CxJiV2Y',
    appId: '1:1061517609461:android:d23f5ac1becfcf6730f8bc',
    messagingSenderId: '1061517609461',
    projectId: 'assignment-1ecbe',
    storageBucket: 'assignment-1ecbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTAAsVRHXtevcy7f2BpV3Y3fxNJ9H81fI',
    appId: '1:1061517609461:ios:cf536f1aca122e5e30f8bc',
    messagingSenderId: '1061517609461',
    projectId: 'assignment-1ecbe',
    storageBucket: 'assignment-1ecbe.appspot.com',
    iosBundleId: 'com.kketann.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTAAsVRHXtevcy7f2BpV3Y3fxNJ9H81fI',
    appId: '1:1061517609461:ios:d86fe0df6e91257d30f8bc',
    messagingSenderId: '1061517609461',
    projectId: 'assignment-1ecbe',
    storageBucket: 'assignment-1ecbe.appspot.com',
    iosBundleId: 'com.kketann.firebaseTutorial.RunnerTests',
  );
}
